# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MissGem' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for MissGem

#  pod 'gRPC', :podspec => "."

pod 'SDWebImage', '~>4.2.2'
pod 'MJRefresh', '~>3.1.15'
pod 'MBProgressHUD', '~>1.0.0'
pod 'IQKeyboardManager', '~>5.0.6'
pod 'RAMAnimatedTabBarController', '~>3.0.0'
pod 'IBAnimatable', '~>5.0.0'
pod 'lottie-ios', '~>2.1.4'
pod 'Realm', '~>3.0.2'
#pod 'JSONModel'
pod 'YTKNetwork', '~>2.0.4'
pod 'MJExtension', '~>3.0.13'
pod 'AFNetworking', '~>3.1.0'
pod 'SAMKeychain', '~>1.5.3'
pod 'HMSegmentedControl', '~>1.5.4'
pod 'Material', '~>2.12.16'
pod 'JazzHands', '~>2.0.8'
pod 'XHLaunchAd'
pod 'IDMPhotoBrowser'
pod 'FSPagerView'

#pod 'FDFullsreenPopGesture'


#pod 'PSTAlertController'
#pod 'UIImage-Helpers'
#pod 'SMPageControl'
#pod 'JTSImageViewController'
#pod 'Pingpp'
#pod 'ELCImagePickerController'
#pod 'BTBadgeView'
#pod 'JSBadgeView'
#pod 'DZNEmptyDataSet'
#pod 'NIMSDK'
pod 'SVProgressHUD', '~>2.2.2'
#pod 'Toast'
#pod 'CocoaLumberjack'
pod 'Reachability', '~>3.2'
#pod 'M80AttributedLabel'
#pod 'FMDB'
#pod 'RSKImageCropper'
#pod 'Aspects'


#pod 'ECSlidingViewController'
#pod 'MFSideMenu'

#添加proto objcetive－c 文件
#pod 'MissGemProto', :path => "../proto"



  target 'MissGemTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Realm/Headers'
  end

  target 'MissGemUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
